apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - preview-ingress.yaml
  - live-ingress.yaml
  - www-redirect-ingress.yaml
  - registry-auth-sealedsecret.yaml
images:
  - name: registry.144.91.77.245.sslip.io/67speedtest
    newTag: 87836d4a1b4b9d634dc35e0a6956c2bbfd004986
