apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - preview-ingress.yaml
  - live-ingress.yaml
  - www-redirect-ingress.yaml
  - registry-auth-sealedsecret.yaml
images:
  - name: registry.144.91.77.245.sslip.io/67speedtest
    newTag: f5ec1bda8265adc0afb0e1620952973e92d1c136
