apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 67speedtest-preview
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: 67speedtest-preview-tls
      hosts:
        - 67speedtest.144.91.77.245.sslip.io
  rules:
    - host: 67speedtest.144.91.77.245.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-67speedtest
                port:
                  number: 80
