---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: 67speedtest-registry-auth
  namespace: 67speedtest
spec:
  encryptedData:
    .dockerconfigjson: AgANjMMdsFLLXoaWURlyoGsfwI+Ze8dUGC0z1448xW1e0UWetq77K4q4/dlXXM4Qp7lpcWwVY/ZD8gTIKaDgOttcVwyaFKpe7RLbUh/dy9otO1sNEqeW+jEuIZIRc9aJlRo3e/VkvFOEB0uwo5+7xSKiFxCEj+P6nELKP2UIwY/nOe6+PCCIVGuGNIg82B7zdkvbpxppI7TtxkDNKGtLqwOO1rPyciVlxfU/EPtfwO38nfYMF9R+aeiaimTJry9k5zgLuOJRz4dGHtPMzHPHh55DkjJbTc9td2AHWu8GwtxfcdZ8yJ7zKqeyDWkNnqf4CaX3jjzhxaYc8nC8bADAEAml3zAkyV15PPlOx22ehTkTXJUco/99fUJ00Z5y0S4BRJQ6yaSPaH2lk6g+A2RtqgwIr0TX0pL7gQFwqkQVt+K55kIXhcs7ThL/aWL5rUR8xOiIxSxHCuSxgMk9N6KaD1u7XYPNU9KOw/ZmuMdT0N4emB9PbChAqGhxfbQhOcQTa1Te5EErWwUcq3ofUIYYFjvFfmUUjj0Lc4zGlcBAtwYXvp7O3nCo9yn8yctLi4iF70w1IiacPt033D0KAlaFmA3sHz4GTiHQpK8UBa9ps1Y30P4MCZgrqqtg3i0/mXiOJSd21cqNBPZF5tQK5KGuZayKcmm39+3OVLiCrE+eR81oQh22awLzXwlZBhg7ihYNTiNFHwJRr3qQyTT10d1F1F5ltj5Mr/dorcnBtvCJD5/n2usX+ztrXHz8lPEXbMdM3rAbKgSD8i+8IDKZZgqIHO/SxGk3oWDVckACWCytJ5ezTQz9DSoBjaV8iCNcy0I80cREWLfZ3Gm5t/Ilg/19a2XuEGwnf9DOq0FjDNIXWKdyK4Rs
  template:
    metadata:
      name: 67speedtest-registry-auth
      namespace: 67speedtest
    type: kubernetes.io/dockerconfigjson
